name: Symfony Rest API

on:
    push:
        branches:
            - master
            - develop
    pull_request:
        branches:
            - master
            - develop
    release:
        types: [published]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Set Elastic data folder rights
              run: chmod 777 var/elasticsearch-data
            - name: Build the docker images
              run: make build-test
            - name: Start the docker images
              run: make start-test
            - name: Check running containers
              run: docker ps -a
            - name: Wait for database connection
              run: make wait-for-db
            - name: Run migrations
              run: make drop-migrate
            - name: Generate keys
              run: make generate-jwt-keys
            - name: Create roles and groups
              run: make create-roles-groups
            - name: Create cron jobs
              run: make migrate-cron-jobs
            - name: Setup transports for Messenger component
              run: make messenger-setup-transports
            - name: Wait for Elastic connection
              run: make wait-for-elastic
            - name: Create or update Elastic index template
              run: make elastic-create-or-update-template
            - name: Run test suite
              run: make phpunit
            - name: Run coding standard
              run: make ecs
            - name: Run codeSniffer
              run: make phpcs
            - name: Run PHPStan
              run: make phpstan
            - name: Run PHPInsights
              run: make phpinsights
            - name: Run php copy past detector
              run: make phpcpd
            - name: Run php mess detector
              run: make phpmd
            - name: Stop the docker images
              run: make stop-test
